#!/bin/bash
#
# compile script for reading battery  & temperature over bluetooth
# paulvha / January 2020 / version 1.0
#
# installation :
#
#  cd bluez-5.52
#
# copy the directory 'btble' with the source files as directory in bluez-5.52
#  cp -r PATH/btble .  # replace PATH with location 
#  cd btble
#  ./make_BTBLE
#
# After compile start : ./btble -b 56:77:88:23:AB:EF -s (with the correct destination address, to read the power supply %)
# or ./btble --help for more options / help information
#
# to get an Bluetooth address run : hcitool lescan
#

# VARIABLES

INCLUDE="-I.. -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I.././lib"
FILES="bt_ble att gatt gattrib utils"
LINK="../btio/btio.o ../lib/.libs/libbluetooth-internal.a ../src/.libs/libshared-glib.a"

# check that supporting files exist
for i in $LINK
do
    if [ ! -f $i ]
    then
        echo "$i was not found"
        echo "First run a complete install for Bluez"
        exit
    fi
done

echo "compiling source files"

for i in $FILES
do
   echo "  $i";
   gcc -DHAVE_CONFIG_H  $INCLUDE -g -O2 -c -o $i.o  $i.c `pkg-config --cflags --libs glib-2.0`

   if [ $? != 0 ]
   then
       exit
   fi
done

echo "linking"

gcc -g -O2 -o btble bt_ble.o att.o gatt.o gattrib.o utils.o $LINK -lglib-2.0

if [ $? != 0 ]
then
   exit
fi

echo "ready : type './btble -s -b 56:77:88:23:AB:EF' (with the correct destination address)"
echo "        to get the power supply percentage or ./btble --help for more options. "
